# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [11]:
len(df.columns)

31

In [12]:
len(X_train) + len(X_test)

569

In [13]:
X_train

array([[-0.5098275 , -0.4199753 , -0.48286875, ..., -0.26422807,
        -0.14229054,  1.5580287 ],
       [-0.56396021, -0.95218413, -0.5912862 , ..., -0.90817913,
        -0.40540928, -0.2445548 ],
       [ 1.70961388,  1.10162617,  2.11667661, ...,  2.05144909,
         4.22248292,  0.87709004],
       ...,
       [-0.80898198, -0.15504315, -0.80770886, ..., -0.45553368,
         0.2590488 , -0.90421412],
       [-1.56940419, -1.13036859, -1.56374536, ..., -1.75040892,
        -0.52031556, -0.30783281],
       [-0.8317747 ,  0.13098979, -0.86789497, ..., -1.32110821,
        -0.57860136, -0.43942869]])

In [14]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [15]:
X_train

array([[-0.5098275 , -0.4199753 , -0.48286875, ..., -0.26422807,
        -0.14229054,  1.5580287 ],
       [-0.56396021, -0.95218413, -0.5912862 , ..., -0.90817913,
        -0.40540928, -0.2445548 ],
       [ 1.70961388,  1.10162617,  2.11667661, ...,  2.05144909,
         4.22248292,  0.87709004],
       ...,
       [-0.80898198, -0.15504315, -0.80770886, ..., -0.45553368,
         0.2590488 , -0.90421412],
       [-1.56940419, -1.13036859, -1.56374536, ..., -1.75040892,
        -0.52031556, -0.30783281],
       [-0.8317747 ,  0.13098979, -0.86789497, ..., -1.32110821,
        -0.57860136, -0.43942869]])

In [16]:
type(y_train)

numpy.ndarray

In [17]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [18]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_251/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_251/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_251/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_251/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [19]:
type(X_train_tensor)

torch.Tensor

# Dataset and Dataloader

In [20]:
from torch.utils.data import Dataset,DataLoader

In [21]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [22]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [23]:
len(train_dataset)

455

In [24]:
train_dataset[2]

(tensor([1.7096, 1.1016, 2.1167, 1.6736, 2.2572, 4.4672, 3.4890, 2.7857, 3.9413,
         2.6584, 1.7768, 1.1218, 2.6535, 1.5675, 1.2302, 2.3798, 2.4198, 2.2569,
         6.8811, 0.8231, 1.4613, 0.9887, 1.8507, 1.3120, 1.3963, 2.2914, 2.3385,
         2.0514, 4.2225, 0.8771]),
 tensor(1.))

#loader

In [25]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the Model

In [26]:
X_train.shape[1]

30

In [27]:
import torch.nn as nn

In [28]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [29]:
torch.rand(30,1)

tensor([[0.7818],
        [0.8161],
        [0.1425],
        [0.1297],
        [0.5248],
        [0.6842],
        [0.8147],
        [0.4600],
        [0.3677],
        [0.8780],
        [0.0868],
        [0.8012],
        [0.5455],
        [0.8404],
        [0.1150],
        [0.2199],
        [0.8663],
        [0.4164],
        [0.1890],
        [0.0754],
        [0.1629],
        [0.8483],
        [0.6752],
        [0.9773],
        [0.8310],
        [0.0606],
        [0.2097],
        [0.9435],
        [0.8769],
        [0.5068]])

# Parameters

In [30]:
X_train_tensor.shape[1]

30

In [31]:
learning_rate = 0.1
epochs = 25

In [32]:
loss_function = nn.BCELoss()

In [33]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [34]:
model = MySimpleNN(X_train_tensor.shape[1])

In [35]:
model.parameters()

In [36]:
X_test_tensor.dtype

torch.float32

In [37]:
model.linear.weight.dtype

torch.float32

In [38]:
y_train_tensor.dtype

torch.float32

In [39]:
model.parameters()

# Training Pipeline

In [40]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.14722108840942383
 2 , Loss = 0.040381696075201035
 3 , Loss = 0.09062887728214264
 4 , Loss = 0.09332064539194107
 5 , Loss = 0.06125330179929733
 6 , Loss = 0.022917592898011208
 7 , Loss = 0.027575133368372917
 8 , Loss = 0.15127229690551758
 9 , Loss = 0.06559880077838898
 10 , Loss = 0.23026207089424133
 11 , Loss = 0.03942536562681198
 12 , Loss = 0.04022476449608803
 13 , Loss = 0.09983454644680023
 14 , Loss = 0.21089230477809906
 15 , Loss = 0.10850570350885391
 16 , Loss = 0.03726506605744362
 17 , Loss = 0.056248314678668976
 18 , Loss = 0.07064970582723618
 19 , Loss = 0.130715474486351
 20 , Loss = 0.036366838961839676
 21 , Loss = 0.10145456343889236
 22 , Loss = 0.0599735789000988
 23 , Loss = 0.06050253286957741
 24 , Loss = 0.022106582298874855
 25 , Loss = 0.06822172552347183

# Training pipeline version 2

In [41]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size

    print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



  #print loss in each epoch

  # print(f" {epoch+1} , Loss = {loss.item()} ")

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

# Model Evaluation (old)

In [42]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5747922658920288

# Better version

In [43]:
y_pred.shape

torch.Size([114, 1])

In [44]:
batch_labels.shape

torch.Size([7])

In [45]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.96875

In [46]:
accuracy_list

[0.9375, 0.96875, 0.96875, 1.0]

# Summary

In [47]:
X_train_tensor.shape

torch.Size([455, 30])

In [48]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [49]:
from torchinfo import summary

In [50]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================